name: "Style check with Vale"
on:
  pull_request:

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: docs/
